.TH "GPIOPin" 3 "Сб 26 Дек 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPIOPin \- Структура вывода для микроконтроллера Эта структура предназначена для управления выводом микроконтроллера  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <struct_code\&.h>\fP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "char \fBRXTX\fP"
.br
.RI "\fIуправление портом \fP"
.in -1c
.SH "Подробное описание"
.PP 
Структура вывода для микроконтроллера Эта структура предназначена для управления выводом микроконтроллера 
.PP
См\&. определение в файле struct_code\&.h строка 15
.SH "Данные класса"
.PP 
.SS "char GPIOPin::RXTX"

.PP
управление портом 
.PP
См\&. определение в файле struct_code\&.h строка 17

.SH "Автор"
.PP 
Автоматически создано Doxygen для My Project из исходного текста\&.
