.TH "GPIOStruct" 3 "Сб 26 Дек 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPIOStruct \- Настройка порта Gpio Эта структура предназначена для управления портом микроконтроллера  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <struct_code\&.h>\fP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "struct GPIOPIn \fBPin\fP [16]"
.br
.RI "\fIвывод микроконтроллера \fP"
.in -1c
.SH "Подробное описание"
.PP 
Настройка порта Gpio Эта структура предназначена для управления портом микроконтроллера 
.PP
См\&. определение в файле struct_code\&.h строка 23
.SH "Данные класса"
.PP 
.SS "struct GPIOPIn GPIOStruct::Pin[16]"

.PP
вывод микроконтроллера 
.PP
См\&. определение в файле struct_code\&.h строка 25

.SH "Автор"
.PP 
Автоматически создано Doxygen для My Project из исходного текста\&.
