.TH "MainWindow" 3 "Сб 26 Дек 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainWindow \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mainwindow\&.h>\fP
.PP
Базовые классы:QMainWindow\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBMainWindow\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~MainWindow\fP ()"
.br
.in -1c
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "QString \fBfile\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
См\&. определение в файле mainwindow\&.h строка 11
.SH "Конструктор(ы)"
.PP 
.SS "MainWindow::MainWindow (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
См\&. определение в файле mainwindow\&.cpp строка 6
.SS "MainWindow::~MainWindow ()"

.PP
См\&. определение в файле mainwindow\&.cpp строка 13
.SH "Данные класса"
.PP 
.SS "QString MainWindow::file"

.PP
См\&. определение в файле mainwindow\&.h строка 18

.SH "Автор"
.PP 
Автоматически создано Doxygen для My Project из исходного текста\&.
