.TH "mainwindow.cpp" 3 "Сб 26 Дек 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mainwindow.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include 'ui_mainwindow\&.h'\fP
.br
\fC#include 'struct_code\&.h'\fP
.br
\fC#include <qfile\&.h>\fP
.br
\fC#include <qfiledialog\&.h>\fP
.br

.SH "Автор"
.PP 
Автоматически создано Doxygen для My Project из исходного текста\&.
