.TH "main.cpp" 3 "Сб 26 Дек 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include <QApplication>\fP
.br

.SS "Функции"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Функции"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
См\&. определение в файле main\&.cpp строка 4
.SH "Автор"
.PP 
Автоматически создано Doxygen для My Project из исходного текста\&.
