.TH "mainwindow.h" 3 "Сб 26 Дек 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mainwindow.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QMainWindow>\fP
.br
\fC#include 'struct_code\&.h'\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.in -1c
.SS "Пространства имен"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для My Project из исходного текста\&.
