.TH "struct_code.h" 3 "Сб 26 Дек 2015" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
struct_code.h \- Файл данных для генератора кода  

.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "struct \fBGPIOPin\fP"
.br
.RI "\fIСтруктура вывода для микроконтроллера Эта структура предназначена для управления выводом микроконтроллера \fP"
.ti -1c
.RI "struct \fBGPIOStruct\fP"
.br
.RI "\fIНастройка порта Gpio Эта структура предназначена для управления портом микроконтроллера \fP"
.ti -1c
.RI "struct \fBOporaDataStruct\fP"
.br
.RI "\fIНастройка опоры Эта структура предназначена для настройки опоры микроконтроллера 1986VE1T\&. \fP"
.in -1c
.SH "Подробное описание"
.PP 
Файл данных для генератора кода 


.PP
\fBАвтор:\fP
.RS 4
Гусенков\&.С\&.В 
.RE
.PP
\fBВерсия:\fP
.RS 4
1\&.0 
.RE
.PP
\fBДата:\fP
.RS 4
23 Декабря 2015 года В этом файле находится набор стрктур для генерации кода 
.RE
.PP

.PP
См\&. определение в файле \fBstruct_code\&.h\fP
.SH "Автор"
.PP 
Автоматически создано Doxygen для My Project из исходного текста\&.
